### PR TITLE
docs: install instructions for Debian and RHEL 9.

### PR DESCRIPTION
**Pull request by ravecat-dev**

### CODE REVIEW

**Comment by AutisticShark** [comment]
Have you actually tried RHEL 9 instructions on the server? That seems missed a lot of key configs.

**Comment by ravecat-dev** [comment]
Screenshot from 2024-05-15 17-51-31
I don't know what you mean by lots of key configs are missing, but I will install the panel on another AlmaLinux server later, and I will detail the process further in the future and will ensure the config doc is more detailed.

**Comment by ravecat-dev** [comment]
oops, wrong click

**Comment by AutisticShark** [comment]
For RHEL 9, you will need to use nginx.org and Redis Lab's Linux mirror since the one in the default repo is always one major version behind. For Debian 12, you will also need to replace the usage of the default package with up to date 3rd party repo because we will drop PHP 8.2 support once PHP 8.4 comes out.

**Pull request merged**
